name: JS

on:
  push:
    branches: [main]
    paths:
      - "impl/js/**"
      - "test/fixtures/v1/**"
      - "package.json"
      - "yarn.lock"
      - ".yarnrc.yml"
  pull_request:
    paths:
      - "impl/js/**"
      - "test/fixtures/v1/**"
      - "package.json"
      - "yarn.lock"
      - ".yarnrc.yml"

defaults:
  run:
    working-directory: impl/js

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test run
